---
platform: linux

image: docker:///golang#1.4.2-wheezy
    
inputs:
  - name: git-repo

outputs:
  - name: artifact-dir
  
caches:
  - path: /root/.m2/

run:
  path: /bin/sh
  args: ["git-repo/ci/tasks/build-artifact.sh"]

