platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: source-code

outputs:
- name: package-output

run:
  path: source-code/todo-service/ci/tasks/package.sh

caches:
  - path: .m2/
  - path: repo/maven
