platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: source-code

outputs:
- name: package-output

run:
  path: /bin/sh
  args: ["source-code/ci/tasks/package.sh"]

caches:
  - path: .m2/
  - path: repo/maven
