---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-git

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/restart.sh

params:
  GIT_REPO_URL:
  PASSWORD:
