---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    
inputs:
  - name: git-repo

caches:
  - path: .m2/
  
run:
  path: /bin/sh
  args: ["git-repo/ci/tasks/unit.sh"]
