  
resources:
- name: source-code
  type: git
  source:
    uri: {{TODO_SERVICE_GIT_REPO}}
    branch: master
    paths:
    - todo-service/**/*
    - todo-service/*

- name: push-TAS-UAT-cloud
  type: cf
  source:
    api: ((TAS_UAT_API))
    username: ((TAS_UAT_USER))
    password: ((TAS_UAT_PASS))
    organization: ((TAS_UAT_ORG))
    space: ((TAS_UAT_SPACE))
    skip_cert_check: false

jobs:
- name: build-jar
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: package
    file: source-code/todo-service/ci/tasks/package.yml
  - put: push-TAS-UAT-cloud
    params:
      manifest: source-code/todo-service/manifest-uat.yml
      path: package-output/app.jar
