  
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/dektlong/todo-service.git
    branch: master

- name: TAS-TEST-cloud
  type: cf
  source:
    api: {{TAS_TEST_API}}
    username: {{TAS_TEST_USER}}
    password: {{TAS_TEST_PASS}}
    organization: {{TAS_TEST_ORG}}
    space: {{TAS_TEST_SPACE}}
    skip_cert_check: true
    
- name: TAS-UAT-cloud
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true
    
- name: TAS-PROD-cloud
  type: cf
  source:
    api: {{TAS_PROD_API}}
    username: {{TAS_PROD_USER}}
    password: {{TAS_PROD_PASS}}
    organization: {{TAS_PROD_ORG}}
    space: {{TAS_PROD_SPACE}}
    skip_cert_check: true

jobs:
- name: test-TODO-SERVICE
  plan:
  - get: source-code
    trigger: true
  - task: package
    file: source-code/ci/tasks/package.yml
  - put: TAS-PROD-cloud
    params:
      manifest: source-code/manifest-prod.yml
      path: package-output/app.jar

- name: integrate-TODO-SERVICE
  plan:
  - get: source-code
    trigger: true
    passed: [test-TODO-SERVICE]
  - task: package
    file: source-code/ci/tasks/package.yml
  - put: TAS-UAT-cloud
    params:
      manifest: source-code/manifest-uat.yml
      path: package-output/app.jar
      
- name: ship-TODO-SERVICE
  serial: true
  plan:
  - get: source-code
    trigger: true
    passed: [integrate-TODO-SERVICE]
  - task: package
    file: source-code/ci/tasks/package.yml
  - put: TAS-PROD-cloud
    params:
      manifest: source-code/manifest-prod.yml
      path: package-output/app.jar   
