resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    PASSWORD: {{GIT_PERSONAL_ACCESS_TOKEN}}
    branch: master

- name: push-TAS-TEST-cloud
  type: cf
  source:
    api: {{TAS_TEST_API}}
    username: {{TAS_TEST_USER}}
    password: {{TAS_TEST_PASS}}
    organization: {{TAS_TEST_ORG}}
    space: {{TAS_TEST_SPACE}}
    skip_cert_check: true

- name: push-TAS-UAT-cloud
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true

- name: push-TAS-PROD-cloud
  type: cf
  source:
    api: {{TAS_PROD_API}}
    username: {{TAS_PROD_USER}}
    password: {{TAS_PROD_PASS}}
    organization: {{TAS_PROD_ORG}}
    space: {{TAS_PROD_SPACE}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: {{S3_VERSION_FILE}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0

- name: release-candidate
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: {{S3_PIPELINE_ARTIFACTS}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

- name: production-release
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: {{S3_DEPLOYMENTS}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

- name: cve-file
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: {{S3_PIPELINE_ARTIFACTS}}
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}


jobs:
- name: init
  plan:
  - get: git-repo
    trigger: true
  - task: init
    file: git-repo/ci/tasks/init.yml

- name: build-TODO-service
  serial_groups: [version]
  serial: true
  plan:
  - get: git-repo
    passed: [init]
    trigger: true
  - get: version
    params: { pre: rc }
  - task: build-artifact
    file: git-repo/ci/tasks/build-artifact.yml
    timeout: 10m
  - put: release-candidate
    params: {file: artifact-dir/dekt-todo*.jar}
  - put: version
    params: {file: version/number}

- name: test-TODO-service
  serial_groups: [version]
  plan:
  - aggregate:
    - get: version
      passed: [build-TODO-service]
      trigger: true
    - get: release-candidate
      passed: [build-TODO-service]
    - get: git-repo
      passed: [build-TODO-service]
  - put: push-TAS-TEST-cloud
    params:
      manifest: git-repo/manifest-test.yml
      current_app_name: dekt-todo-service-test
      path: release-candidate/dekt-todo*.jar

- name: integrate-TODO-service
  serial_groups: [version]
  plan:
  - aggregate:
    - get: release-candidate
      passed: [test-TODO-service]
      trigger: true
    - get: version
      passed: [test-TODO-service]
    - get: git-repo
      passed: [test-TODO-service]
  - put: push-TAS-UAT-cloud
    params:
      manifest: git-repo/manifest-uat.yml
      current_app_name: dekt-todo-service-uat
      path: release-candidate/dekt-todo*.jar

- name: ship-TODO-service
  serial_groups: [version]
  serial: true
  plan:
  - aggregate:
    - get: release-candidate
      passed: [integrate-TODO-service]
      trigger: true
    - get: version
      params: { bump: final }
      passed: [integrate-TODO-service]
    - get: git-repo
      passed: [integrate-TODO-service]
  - task: prepare-final
    file: git-repo/ci/tasks/prepare-final.yml
    params:
      base_name: dekt-todo
  - put: production-release
    params:
      file: final-dir/dekt-todo*.jar
  - put: push-TAS-PROD-cloud
    params:
      manifest: git-repo/manifest-prod.yml
      current_app_name: dekt-todo-service
      path: final-dir/dekt-todo*.jar

- name: major
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: major, pre: rc }

- name: minor
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: minor, pre: rc }

- name: patch-TODO-service
  serial_groups: [ version ]
  plan:
  - get: cve-file
  - get: version
    passed: [ ship-TODO-service ]
    trigger: true
  - put: version
    params: { bump: patch }
