resources:
- name: todo-ui-docker-image
  type: docker-image
  source:
    username: ((harbor-username))
    password: ((harbor-password))
    repository: harbor.apps.cf.tanzutime.com/demo/todo-ui
    email: ((harbor-email))

- name: source-code
  type: git
  source:
    uri: https://github.com/odedia/todo-ui.git
    branch: master

- name: cf-push-resource
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-user))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: push-to-pcf
  public: true
  serial: true
  plan:
  - get: source-code
  - get: todo-ui-docker-image
    trigger: true
  - put: cf-push-resource
    params:
      manifest: source-code/manifest-docker.yml

