  
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/dektlong/todo-service.git
    branch: master

- name: TAS-UAT-cloud
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true

jobs:
- name: uat-TODO-SERVICE
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: package
    file: source-code/ci/tasks/package.yml
  - put: TAS-UAT-cloud
    params:
      manifest: source-code/manifest-uat.yml
      path: package-output/app.jar
      
